pub mod backup;
pub mod bridge;
pub mod config;
pub mod event_handler;
mod governed_client;
pub mod imap;
pub mod mail;
pub mod mcp;
mod net;
pub mod smtp;
pub mod store;
pub mod sync;
pub mod tls;
pub mod tuta;
pub mod util;
